### ISSUE TITLE
データベースに最初からセットされているテストユーザーの情報が引っ張ってこれない

### ISSUE THREAD

**Issue by toco1001** [YoshikiIkegaya/mercury#30]
データベースに最初からセットされているテストユーザーの情報が引っ張ってこれない。

おそらくユーザー情報の格納の形式が違うためだと思われる

**Comment by toco1001** [comment]
正常時

`===== [Fetch User Info API] ======
[
  {
    "email" : "test@gmail.com",
    "id" : 2,
    "image_url" : "http:\/\/free-designer.net\/design_img\/1229010007.jpg",
    "name" : "Test User",
    "updated_at" : "2017-01-25 08:36:55",
    "created_at" : "2017-01-25 08:36:55"
  }
]
1
("0", {
  "name" : "Test User",
  "email" : "test@gmail.com",
  "id" : 2,
  "image_url" : "http:\/\/free-designer.net\/design_img\/1229010007.jpg",
  "updated_at" : "2017-01-25 08:36:55",
  "created_at" : "2017-01-25 08:36:55"
})
===========`

**Comment by toco1001** [comment]
異常時

> =====

 [Fetch User Info API] ======
[

]
0
===========

**Comment by YoshikiIkegaya** [comment]
とれないテストユーザのID,Wanted!
